version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back-db

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - back-db
      - back-redis-worker

  worker:
    build:
      context: ./Backend
      dockerfile: Dockerfile_worker
    container_name: worker_redis
    depends_on:
      - redis
    shm_size: '1gb'
    networks:
      - back-redis-worker
      - frontend-backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - back-db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_SEND_VIDEO
    container_name: react_app
    ports:
      - "80:80"
    env_file:
      - ./Frontend/video-uploader/.env
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend-backend

  back:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "8080:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - back-db
      - frontend-backend
      - back-redis-worker

networks:
  frontend-backend:
  back-db:
  back-redis-worker:

volumes:
  db_data:
